controller:
    watchIngressWithoutClass: true

    hostNetwork: true
    hostPort:
        enabled: true
    kind: DaemonSet
    # kind: Deployment
    # replicaCount: 1
    service:
        type: NodePort
        nodePorts:
            http: 32080
            https: 32443
