helmCharts:
  - name: ingress-nginx
    includeCRDs: false
    valuesFile: ingress-values.yaml
    releaseName: ingress-nginx
    version: "4.0.17"
    repo: https://kubernetes.github.io/ingress-nginx
  - name: metrics-server
    includeCRDs: false
    valuesFile: metrics-server-values.yaml
    releaseName: metrics-server
    version: "3.8.2"
    repo: https://kubernetes-sigs.github.io/metrics-server/
